<?php

namespace AppBundle\Repository;

/**
 * Finalized_OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Finalized_OrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
