<?php

namespace AppBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCartOrderByRegisteredUserId($id)
    {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT o FROM AppBundle\Entity\Orders o WHERE o.registeredOwner = :id and o.status = :status");
        $query->setParameters(array(
            'id'      => $id,
            'status'  => 1
        ));
        
        $order = $query->getResult();
        
        return $order;
    }
}
