<?php

namespace AppBundle\Repository;

/**
 * Product_ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
