<?php

namespace AppBundle\Repository;

/**
 * Shipping_OptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Shipping_OptionRepository extends \Doctrine\ORM\EntityRepository
{
}
