<?php

namespace AppBundle\Repository;

/**
 * User_Not_RegisteredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_Not_RegisteredRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotRegisteredUserByIpAddress($ip)
    {        
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT u FROM AppBundle\Entity\User_Not_Registered u WHERE u.clientIp = :ip");
        $query->setParameter('ip', $ip);
        
        $notRegisteredUser = $query->getResult();
        
        return $notRegisteredUser;
    }
}
