<?php

namespace AppBundle\Repository;

/**
 * User_Not_RegisteredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_Not_RegisteredRepository extends \Doctrine\ORM\EntityRepository
{
}
