<?php

namespace AppBundle\Repository;

/**
 * User_Not_RegisteredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_Not_RegisteredRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotRegisteredUserByIpAddress($ip)
    {        
        $em = $this->getEntityManager();
        
        $query = $em->createQueryBuilder()
                    ->select('u')
                    ->from('AppBundle\Entity\User_Not_Registered', 'u')
                    ->where('u.clientIp = :ip')
                    ->setParameter('ip', $ip)
                ;
        
        $notRegisteredUser = $query->getQuery()
                                   ->getOneOrNullResult();
        
        return $notRegisteredUser;
    }
}
