security:
    
    providers:
        db_provider:
            entity: 
                class: AppBundle:User
                property: email
                
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:            
            anonymous: ~

            form_login:
                login_path: login
                check_path: login
            
            provider: db_provider
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customers, roles: ROLE_USER }
